{
  "dataType": "CVE_RECORD",
  "dataVersion": "5.1",
  "cveMetadata": {
    "cveId": "CVE-2025-5455",
    "assignerOrgId": "a59d8014-47c4-4630-ab43-e1b13cbe58e3",
    "state": "PUBLISHED",
    "assignerShortName": "TQtC",
    "dateReserved": "2025-06-02T08:31:36.081Z",
    "datePublished": "2025-06-02T08:46:20.524Z",
    "dateUpdated": "2025-06-02T08:46:20.524Z"
  },
  "containers": {
    "cna": {
      "affected": [
        {
          "defaultStatus": "unaffected",
          "product": "Qt",
          "vendor": "The Qt Company",
          "versions": [
            {
              "lessThanOrEqual": "5.15.18",
              "status": "affected",
              "version": "0",
              "versionType": "python"
            },
            {
              "lessThanOrEqual": "6.5.8",
              "status": "affected",
              "version": "6.0.0",
              "versionType": "python"
            },
            {
              "status": "unaffected",
              "version": "6.5.9",
              "versionType": "python"
            },
            {
              "lessThanOrEqual": "6.8.3",
              "status": "affected",
              "version": "6.6.0",
              "versionType": "python"
            },
            {
              "status": "unaffected",
              "version": "6.8.4",
              "versionType": "python"
            },
            {
              "status": "affected",
              "version": "6.9.0",
              "versionType": "python"
            },
            {
              "status": "unaffected",
              "version": "6.9.1",
              "versionType": "python"
            }
          ]
        }
      ],
      "descriptions": [
        {
          "lang": "en",
          "supportingMedia": [
            {
              "base64": false,
              "type": "text/html",
              "value": "<p>An issue was found in the private API function qDecodeDataUrl() in QtCore, which is used in QTextDocument and QNetworkReply, and, potentially, in user code.</p><p>If the function was called with malformed data, for example, an URL that\ncontained a \"charset\" parameter that lacked a value (such as\n\"data:charset,\"), and Qt was built with assertions enabled, then it would hit an assertion, resulting in a denial of service\n(abort).</p><p>This impacts Qt up to 5.15.18, 6.0.0-&gt;6.5.8, 6.6.0-&gt;6.8.3 and 6.9.0. This has been fixed in 5.15.19, 6.5.9, 6.8.4 and 6.9.1.</p><br>"
            }
          ],
          "value": "An issue was found in the private API function qDecodeDataUrl() in QtCore, which is used in QTextDocument and QNetworkReply, and, potentially, in user code.\n\nIf the function was called with malformed data, for example, an URL that\ncontained a \"charset\" parameter that lacked a value (such as\n\"data:charset,\"), and Qt was built with assertions enabled, then it would hit an assertion, resulting in a denial of service\n(abort).\n\nThis impacts Qt up to 5.15.18, 6.0.0->6.5.8, 6.6.0->6.8.3 and 6.9.0. This has been fixed in 5.15.19, 6.5.9, 6.8.4 and 6.9.1."
        }
      ],
      "metrics": [
        {
          "cvssV4_0": {
            "Automatable": "NOT_DEFINED",
            "Recovery": "USER",
            "Safety": "NOT_DEFINED",
            "attackComplexity": "LOW",
            "attackRequirements": "NONE",
            "attackVector": "NETWORK",
            "baseScore": 8.4,
            "baseSeverity": "HIGH",
            "privilegesRequired": "NONE",
            "providerUrgency": "CLEAR",
            "subAvailabilityImpact": "HIGH",
            "subConfidentialityImpact": "NONE",
            "subIntegrityImpact": "HIGH",
            "userInteraction": "ACTIVE",
            "valueDensity": "NOT_DEFINED",
            "vectorString": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:A/VC:N/VI:H/VA:H/SC:N/SI:H/SA:H/R:U/RE:M/U:Clear",
            "version": "4.0",
            "vulnAvailabilityImpact": "HIGH",
            "vulnConfidentialityImpact": "NONE",
            "vulnIntegrityImpact": "HIGH",
            "vulnerabilityResponseEffort": "MODERATE"
          },
          "format": "CVSS",
          "scenarios": [
            {
              "lang": "en",
              "value": "GENERAL"
            }
          ]
        }
      ],
      "problemTypes": [
        {
          "descriptions": [
            {
              "cweId": "CWE-20",
              "description": "CWE-20 Improper Input Validation",
              "lang": "en",
              "type": "CWE"
            }
          ]
        }
      ],
      "providerMetadata": {
        "orgId": "a59d8014-47c4-4630-ab43-e1b13cbe58e3",
        "shortName": "TQtC",
        "dateUpdated": "2025-06-02T08:46:20.524Z"
      },
      "references": [
        {
          "url": "https://codereview.qt-project.org/c/qt/qtbase/+/642006"
        }
      ],
      "source": {
        "discovery": "INTERNAL"
      },
      "title": "Possible denial of service when passing malformed data in a URL to qDecodeDataUrl",
      "x_generator": {
        "engine": "Vulnogram 0.2.0"
      }
    }
  }
}